version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - /tmp:/tmp
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/database
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongo

volumes:
  mongo_data:
    driver: local
